# arch/arm/mach-s3c2440/Makefile
#
# Copyright 2007 Simtec Electronics
#
# Licensed under GPLv2

obj-y				:=
obj-m				:=
obj-n				:=
obj-				:=

obj-$(CONFIG_CPU_S3C2440)	+= dsc.o

obj-$(CONFIG_S3C2440_CPUFREQ)	+= s3c2440-cpufreq.o

obj-$(CONFIG_S3C2440_PLL_12000000) += s3c2440-pll-12000000.o
obj-$(CONFIG_S3C2440_PLL_1693.4.1) += s3c2440-pll-1693.4.1.o
